server:
  port: 22320
spring:
  application:
    name: coupon-calculation
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.242.129:8848
        service: coupon-calculation-ser
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        metadata:
          mydata: abc
        naming-load-cache-at-start: false
        namespace: dev
        cluster-name: Cluster-A
        group: myGroup
        register-enabled: true
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.242.129:8080
      web-context-unify: false



  sleuth:
    sampler:
      probability: 1.0
      rate: 1000
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
      addresses: 192.168.242.130:5672
  rabbitmq:
    host: 192.168.242.130
    port: 5672
    username: yesj
    password: yesj
