# 项目启动端口
server:
  port: 22319
spring:
  application:
    #项目名称
    name: coupon-template-ser
    # 项目名称
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hinernate.show_sql: true
    open-in-view: false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.242.129:8848
        service: coupon-template-ser
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        metadata:
          mydata: abc
        naming-load-cache-at-start: false
        namespace: dev
        cluster-name: Cluster-A
        group: myGroup
        register-enabled: true
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.242.129:8080
      web-context-unify: false
  rabbitmq:
    host: 192.168.242.130
    port: 5672
    username: yesj
    password: yesj
  sleuth:
    sampler:
      probability: 1.0
      rate: 1000
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: 192.168.242.130:5672
      queue: zipkin
