# 项目启动端口
server:
  port: 22321
spring:
  application:
    #项目名称
    name: coupon-customer-ser
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hinernate.show_sql: false
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.242.129:8848
        service: coupon-customer-ser
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        metadata:
          mydata: abc
        naming-load-cache-at-start: false
        namespace: dev
        cluster-name: Cluster-A
        group: myGroup
        register-enabled: true
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.242.129:8080
      web-context-unify: false
  sleuth:
    sampler:
      probability: 1.0
      rate: 1000
  rabbitmq:
    host: 192.168.242.130
    port: 5672
    username: yesj
    password: yesj
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: 192.168.242.130:5672
      queue: zipkin
# feign接口类日志级别设置
logging:
  level:
    com.fortune.coupon.customer.feign.CalculationService: debug
    com.fortune.coupon.customer.feign.TemplateService: debug
# feign设置
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 5000
      coupon-template-ser:
        connectTimeout: 1000
        readTimeout: 2000
  circuitbreaker:
    enabled: true
