# 项目启动端口
server:
  port: 22321
spring:
  application:
    #项目名称
    name: coupon-customer-serv
    # 项目名称
  datasource:
    username: root
    password: yesjer
    url: jdbc:mysql://192.168.242.129:3306/coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull

    # 数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 数据库连接池参数配置，比如池子大小、超时时间、是否自动提交等等
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: fortuneCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hinernate.show_sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.242.129:8848
        service: coupon-customer-ser
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        metadata:
          mydata: abc
        naming-load-cache-at-start: false
        namespace: dev
        cluster-name: Cluster-A
        group: myGroup
        register-enabled: true
# feign接口类日志级别设置
logging:
  level:
    com.fortune.coupon.customer.feign.CalculationService: debug
    com.fortune.coupon.customer.feign.TemplateService: debug
# feign设置
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 5000
      coupon-template-ser:
        connectTimeout: 1000
        readTimeout: 2000
  circuitbreaker:
    enabled: true
